apiVersion: v1
kind: Service
metadata:
  name: get-country-code
spec:
  selector:
    app: get-country-code
  ports:
  - port: 8000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-country-code
spec:
  selector:
    matchLabels:
      app: get-country-code
  replicas: 1
  template:
    metadata:
      labels:
        app: get-country-code
    spec:
      containers:
      - name: get-country-code
        image: ranjitkumar518/get-country-code:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
